events/urls.py
from django.urls import path
from .views import events_main

app_name = 'events'
urlpatterns = [
    path('', events_main, name='events_main'),
]

movies/urls.py
from django.urls import path
from .views import movies_main, vod, upload_movies, credentials, update_vod, \
    add_genre_like, vod_list, movie_details, change_wts_who, import_update, temp_function, \
    update_recommendation

app_name = 'movies'
urlpatterns = [
    path('', movies_main, name='movies_main'),
    path('vod/', vod, name='vod'),
    path('vod/<who>/<vod_service>/', vod_list, name='vod_list'),
    path('import-update/', import_update, name='import_update'),
    path('genres/', add_genre_like, name='genres'),
    path('credentials/', credentials, name='credentials'),
    path('update_vod:<upload_url>/', update_vod, name='update_vod'),
    path('upload_wts:<upload_url>/', upload_movies, name='upload_wts'),
    path('upload_rated:<upload_url>/', upload_movies, name='upload_rated'),
    path('update_recommendation:<upload_url>/', update_recommendation, name='update_recommendation'),
    path('temp_function:<upload_url>/', temp_function, name='temp_function'),
    path('change_wts_who:<movie_id>/<who>/<vod_service>/', change_wts_who, name='change_wts_who'),
    path('<movie_id>/', movie_details, name='movie_details'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import main, movies_main

# def main(request):
#     render(request, "main.html", {'test': 'test'})

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', main),
    path('', movies_main),
    path('movies/', include('movies.urls')),
    path('events/', include('events.urls')),
]

movies/forms.py
# from crispy_forms.bootstrap import FormActions
from django import forms
# from django.forms import modelformset_factory, inlineformset_factory
from .models import FilmwebCredentials, Genre
from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Field, Submit
import datetime as dt


class CredentialsForm(forms.ModelForm):

    class Meta:
        model = FilmwebCredentials
        fields = ['user_name', 'cookie', 'user_agent']


class GenreForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GenreForm, self).__init__(*args, **kwargs)
        self.fields['genre'].widget.attrs['readonly'] = True

    @property
    def helper(self):
        helper = FormHelper()
        helper.form_class = "col-md-3"
        helper.layout = Layout(
            Field('genre', readonly=True, style="background-color: rgb(240 ,240, 240);"),
            'like',
        )
        helper.add_input(Submit('save', 'Save', css_class='mb-3 btn-primary btn-lg rounded-pill'))
        helper.form_method = "POST"
        helper.template = 'bootstrap/table_inline_formset.html'
        return helper

    class Meta:
        model = Genre
        fields = ['genre', 'like', 'short']


class MyRateForm(forms.Form):
    my_rate = forms.IntegerField(min_value=1, max_value=10)


class MoviesSearch(forms.Form):
    year_now = dt.datetime.now().year

    movies_set_choices = (('wts', 'WTS'), ('rated', 'rated'), ('all', 'all'))
    movies_set = forms.ChoiceField(label="Set of movies", choices=movies_set_choices, initial='WTS')
    votes_from = forms.IntegerField(label="Votes No. from", initial=0, min_value=0)
    box_office_min = forms.IntegerField(label="Box office from", initial=0, min_value=0)
    oscar_award = forms.ChoiceField(label="Oscars", choices=(('all', 'all'), ('yes', 'yes')), initial='all')
    vod_set_choices = (('all', 'all'), ('yes', 'yes'), ('other', 'other'), ('no', 'no'))
    vod_set = forms.ChoiceField(label="on VOD", choices=vod_set_choices, initial='yes')
    year_from = forms.IntegerField(label="Year from", initial=1940, min_value=1940, max_value=year_now)
    year_to = forms.IntegerField(label="Year to", initial=year_now, min_value=1940, max_value=year_now)

movies/views.py
import random
import string

# from django.core.paginator import Paginator
from django.shortcuts import render, redirect
# from django.contrib.auth import login, authenticate, logout
# from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth.models import User
from django.contrib import messages
from django.forms import modelformset_factory

from .service_db import movies_db_save, vod_db_update, wts_who_db_change, temp_db, my_rate_db_update, \
    set_recommendation, check_authentication_decorator, check_authentication
from .service_select import select_vod, select_movies
from .forms import CredentialsForm, GenreForm, MyRateForm, MoviesSearch
from .models import FilmwebCredentials, Movie, Genre

# import logging
# logging.basicConfig(level=logging.DEBUG)


def main(request):
    return render(request, "main.html", {'main': 'main'})


def movies_main(request):
    if request.method == "GET":
        form = MoviesSearch(request.GET)
        if form.is_valid():
            movies_listing, kind = select_movies(form.cleaned_data)
            context = {
                'movies': True,
                'movies_lists': True,
                'kind': kind,
                'movies_listing': movies_listing,
            }
            return render(request, "movies/listing_kind.html", context)

    form = MoviesSearch()
    context = {
        'movies': True,
        'movies_list': True,
        'form': form,
    }
    return render(request, "movies/main.html", context)


def vod(request):
    vod_services = ['Netflix', 'HBO', 'Amazon', 'Disney', 'Canal+', 'Apple', 'Other VOD', 'Not on VOD']
    who_list = ['kk', 'kz', 'all']
    context = {
        'movies': True,
        'movies_vod': True,
        'vod_services': vod_services,
        'who_list': who_list,
    }

    return render(request, "movies/vod.html", context)


def vod_list(request, who, vod_service):
    movies_listing, vod_service_name = select_vod(who, vod_service)
    context = {
        'movies': True,
        'movies_vod': True,
        'who': who,
        'vod_service_name': vod_service_name,
        'movies_listing': movies_listing,
    }
    return render(request, "movies/listing_vod.html", context)


def movie_details(request, movie_id):
    movie = Movie.objects.get(movie_id=movie_id)
    if request.method == "POST":
        form = MyRateForm(data=request.POST)
        if form.is_valid() and check_authentication(request):
            my_rate = form.cleaned_data.get('my_rate')
            my_rate_db_update(movie, my_rate)
            messages.success(request, "My rate has been saved")
        return redirect(request.path)
    else:
        form = MyRateForm
    context = {
        'movies': True,
        'movie': movie,
        'form': form,
    }
    return render(request, "movies/movie_details.html", context)


def import_update(request):
    upload_url = ''.join(random.choices(string.ascii_lowercase + string.digits, k=10))
    context = {
        'movies': True,
        'import_update': True,
        'upload_url': upload_url,
    }
    return render(request, "movies/import_update.html", context)


def add_genre_like(request):
    GenreFormSet = modelformset_factory(Genre, form=GenreForm, extra=0)
    helper = GenreForm().helper
    if request.method == 'POST':
        form = GenreFormSet(data=request.POST)
        if check_authentication(request):
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Data has been saved')
        return redirect("movies:movies_main")
    form = GenreFormSet()

    context = {
        'movies': True,
        'genre': True,
        'form': form,
        'helper': helper,
    }
    return render(request, "movies/genres.html", context)


def credentials(request):
    if check_authentication(request):
        user_obj = FilmwebCredentials.objects.get(user=request.user)
        if request.method == 'POST':
            form = CredentialsForm(data=request.POST)
            if form.is_valid():
                FilmwebCredentials.objects.update_or_create(
                    user=request.user,
                    defaults={
                        'user_name': form.cleaned_data.get('user_name'),
                        'cookie': form.cleaned_data.get('cookie'),
                        'user_agent': form.cleaned_data.get('user_agent')
                    }
                )
                messages.add_message(request, messages.SUCCESS, 'Data has been saved')
            return redirect("movies:movies_main")
        else:
            form = CredentialsForm(data={
                'user_name': user_obj.user_name,
                'cookie': user_obj.cookie,
                'user_agent': user_obj.user_agent
            })
    else:
        form = CredentialsForm
    context = {
        'movies': True,
        'credentials': True,
        'form': form,
    }
    return render(request, "movies/credentials.html", context)


@check_authentication_decorator
def update_vod(request, upload_url):
    log_vod = vod_db_update()
    context = {
        'movies': True,
        'movies_upload': True,
        'log_vod': log_vod,
    }
    return render(request, "movies/import_update_result.html", context)


@check_authentication_decorator
def upload_movies(request, upload_url):
    user = FilmwebCredentials.objects.get(user=request.user).user_name

    log_info = ''
    kind = ''
    if 'upload_rated' in request.path:
        movies_saved, movies_not_saved, new_genre = movies_db_save('movies_rated', user)
    elif 'upload_wts' in request.path:
        movies_saved, movies_not_saved, new_genre = movies_db_save('movies_wts', user)
        log_info = set_recommendation()
        kind = 'wts'
    else:
        movies_saved, movies_not_saved, new_genre = [], [], []
    context = {
        'movies': True,
        'movies_upload': True,
        'movies_saved': movies_saved,
        'movies_not_saved': movies_not_saved,
        'new_genre': new_genre,
        'log_info': log_info,
        'kind': kind,
    }
    return render(request, "movies/import_update_result.html", context)


@check_authentication_decorator
def update_recommendation(request, upload_url):
    log_info = set_recommendation()
    context = {
        'movies': True,
        'movies_upload': True,
        'log_info': log_info,
    }
    return render(request, "movies/import_update_result.html", context)


@check_authentication_decorator
def change_wts_who(request, movie_id, who, vod_service):
    wts_who_db_change(movie_id, who)
    return redirect('movies:vod_list', who=who, vod_service=vod_service)


@check_authentication_decorator
def temp_function(request, upload_url):
    log = temp_db()
    context = {
        'log': log,
    }
    return render(request, "movies/import_update_result.html", context)

templates/movies/genres.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}


{% block title %}Add genre like{% endblock %}
{% block content %}
{% include "movies/nav.html" %}

    <div class="h1">Add like to genre</div>
    <div class="mb-1">Assess in 1-5 scale how much do you like a genre.
        It would have influence on recommendation engine</div>

    {% crispy form helper %}

{% endblock %}

templates/movies/import_update.html
{% extends "base.html" %}

{% block title %}Main{% endblock %}
{% block content %}
    {% include "movies/nav.html" %}

    <div class="h1">Manage database</div>

    <div class="d-flex align-items-center mt-3">
        <button class="btn btn-outline-primary btn-lg rounded-pill">
            <a href="{% url 'movies:update_vod' upload_url %}">Update</a></button>
        <label class="ms-3 fs-5">Update VOD information from movie portal in all WTS movies</label>
    </div>

    <div class="d-flex align-items-center mt-3">
        <button class="btn btn-outline-primary btn-lg rounded-pill">
            <a href="{% url 'movies:upload_wts' upload_url %}">Upload</a></button>
        <label class="ms-3 fs-5">
            Upload WTS (want to see) movies from movie portal and update recommendation rate, actor rate</label>
    </div>

    <div class="d-flex align-items-center mt-3">
        <button class="btn btn-outline-primary btn-lg rounded-pill">
            <a href="{% url 'movies:update_recommendation' upload_url %}">Update</a></button>
        <label class="ms-3 fs-5">Update recommendation rate, actor rate for all WTS movies</label>
    </div>

    <div class="d-flex align-items-center mt-3">
        <button class="btn btn-outline-primary btn-lg rounded-pill">
            <a href="{% url 'movies:upload_rated' upload_url %}">Upload</a></button>
        <label class="ms-3 fs-5">!!! only once !!! Upload rated movies from movie portal</label>
    </div>

    {% if user.is_authenticated %}
        <div class="d-flex align-items-center mt-3">
            <button class="btn btn-outline-primary btn-lg rounded-pill">
                <a href="{% url 'movies:temp_function' upload_url %}">Run</a></button>
            <label class="ms-3 fs-5">Run temporary function</label>
        </div>
    {% endif %}

{% endblock %}

templates/movies/main.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %}Main{% endblock %}
{% block content %}
    {% include "movies/nav.html" %}

    <div class="h1">List of movies</div>

<form method="get">
    <div class="d-flex align-items-center my-3">
        <button class="btn btn-outline-primary rounded-pill col-md-2" type="submit">
            Select movies</button>
        <label class="ms-3 fs-5">Select movies based on following criteria:</label>
    </div>

    <div class="mt-3">
        {% bootstrap_form form layout='horizontal' horizontal_label_class='col-md-2' horizontal_field_class='col-md-2' %}
    </div>
</form>

{% endblock %}

templates/movies/movie_details.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load custom_tags %}
{% load humanize %}

{% block title %}Movies' list{% endblock %}
{% block content %}
{% include "movies/nav.html" %}

<div class="h1"> {{ movie.title }}</div>

<div class="row">
    <div class="col-md-10">
        <div><a href="{{ movie.link }}">{{ movie.movie_id }}</a></div>
        <div>Director: {{ movie.director }}</div>
        <div>Genres: {{ movie.genres.all|get_flat_values_queryset:'genre,, ' }}</div>
        <div>Production: {{ movie.countries.all|get_flat_values_queryset:'country,, ' }}</div>
        {% if movie.vods.all|length > 0 %}
            <div>VODs: {{ movie.vods.first.vod_list_comma }}</div>
        {% endif %}
    </div>
    <div class="col-md-2 text-center">
        {% if not movie.my_rates.rate %}
            <form method="POST">
                {% csrf_token %}
                <div> {{ form.my_rate.label }} </div>
                <div> {{ form.my_rate }} </div>
                <div class="my-1">
                    <button class="btn btn-outline-primary btn-sm rounded-pill" type="submit">Save</button></div>
            </form>
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-md-3">
    <table class="table table-hover table-sm table-responsive text-start">
        <thead>
            <tr>
                <th>&nbsp</th>
                <th>&nbsp</th>
            </tr>
        </thead>

        <tbody class="container overflow-auto">
            {% if movie.wtss.rate %}
                <tr>
                    <td>Want to see</td>
                    <td class="text-center">{{ movie.wtss.rate }}</td>
                </tr>
                <tr>
                    <td>Recommendation rate</td>
                    <td class="text-center">{{ movie.wtss.rate_recommended|floatformat:1 }}</td>
                </tr>
            {% else %}
                <tr>
                    <td>My rate</td>
                    <td class="text-center">{{ movie.my_rates.rate }}</td>
{#                    <td class="text-center">{{ movie.user_rate }}</td>#}
                </tr>
            {% endif %}
            <tr>
                <td>Rate</td>
                <td class="text-center">{{ movie.rate|floatformat:1 }}</td>
            </tr>
            <tr>
                <td>Rate count</td>
                <td class="text-center">{{ movie.rate_count|intcomma }}</td>
            </tr>
            {% if movie.critic_rate %}
                <tr>
                    <td>Critic rate</td>
                    <td class="text-center">{{ movie.critic_rate }}</td>
                </tr>
            {% endif %}
            <tr>
                <td>Year</td>
                <td class="text-center">{{ movie.year }}</td>
            </tr>
            {% if movie.box_office %}
                <tr>
                    <td>Box office</td>
                    <td class="text-center">{{ movie.box_office }}</td>
                </tr>
            {% endif %}
            {% if movie.box_office_usa %}
            <tr>
                <td>Box office (USA)</td>
                <td class="text-center">{{ movie.box_office_usa }}</td>
            </tr>
            {% endif %}
            {% if movie.box_office_outside_usa %}
            <tr>
                <td>Box office (outside USA)</td>
                <td class="text-center">{{ movie.box_office_outside_usa }}</td>
            </tr>
            {% endif %}
            {% if movie.award_oscar %}
            <tr>
                <td>Oscars</td>
                <td class="text-center">{{ movie.award_oscar }}</td>
            </tr>
            {% endif %}
            {% if movie.award %}
            <tr>
                <td>Awards</td>
                <td class="text-center">{{ movie.award }}</td>
            </tr>
            {% endif %}
            {% if movie.nomination %}
            <tr>
                <td>Nominations</td>
                <td class="text-center">{{ movie.nomination }}</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    </div>

    <div class="col-md-1"></div>

    <div class="col-md-6">
        <table class="container table col-md-4 table-hover table-sm table-responsive text-center">
        <thead>
            <tr>
                <th class="text-start">Actor</th>
                <th>Rate</th>
                <th>Rate count</th>
                <th>My rate</th>
                <th>TOP #</th>
            </tr>
        </thead>

        <tbody class="container overflow-auto">
            {% for role in movie.roles.all|order_by:'-rate' %}
            <tr>
                <td class="text-start"><a href="{{ role.actor.link }}">{{ role.actor }}</a></td>
                <td>{{ role.rate }}</td>
                <td>{{ role.rate_count|intcomma }}</td>
                <td>{{ role.user_rate|floatformat:"0" }}</td>
                <td>{{ role.top|floatformat:"0" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/movies/nav.html
<div class="row container py-2">

<nav class="nav col-md-6">
    <a href="{% url 'movies:movies_main' %}" class="nav-link {% if movies_list %} active bg-light rounded-pill"
        aria-current="page {% endif %} ">Movies' list</a>
    <a href="{% url 'movies:vod' %}" class="nav-link {% if movies_vod %} active bg-light rounded-pill"
        aria-current="page {% endif %} ">VOD</a>
</nav>
<nav class="nav col-md-6 justify-content-end">
    <a href="{% url 'movies:import_update' %}" class="nav-link {% if import_update %} active bg-light rounded-pill"
        aria-current="page {% endif %} ">Imports/Updates</a>
    <a class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">Configuration</a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a href="{% url 'movies:genres' %}" class="nav-link {% if genre %}
                    active  bg-light" aria-current="page {% endif %} ">Genres</a></li>
            <li><a href="{% url 'movies:credentials' %}" class="nav-link {% if credentials %}
                    active  bg-light" aria-current="page {% endif %} ">Credentials</a></li>
          </ul>
    </a>
</nav>
</div>

templates/movies/vod.html
{% extends "base.html" %}

{% block title %}VOD{% endblock %}
{% block content %}
{% include "movies/nav.html" %}

    <div class="row">
    {% for who in who_list %}
        <div class="container col-md-3">
            <div class="h1 text-center w-50">{{ who }}</div>

            {% for vod in vod_services %}
                <div><button class="my-1 w-50 btn btn-sm btn-outline-primary bg-white rounded-pill">
                    <a href="{% url 'movies:vod_list' who vod|slugify %}">{{ vod }}</a></button></div>
            {% endfor %}
        </div>
        <div class="container col-md-1"></div>
    {% endfor %}
    </div>

{% endblock %}